module.exports = {
  mode: 'jit',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        downtiplx: {
          50: '#fef9ec',
          100: '#fdeec4',
          200: '#fbd97b',
          300: '#f8c130',
          400: '#E5A00D',
          500: '#CC7B19',
          600: '#a55a10',
          700: '#7c3f0c',
          800: '#512808',
          900: '#2a1404',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
      },
      boxShadow: {
        'glow-sm': '0 0 24px rgba(229, 160, 13, 0.18)',
        glow: '0 0 36px rgba(229, 160, 13, 0.30)',
        'glow-lg': '0 0 60px rgba(229, 160, 13, 0.45)',
      },
      animation: {
        'fade-in': 'fadeIn 0.35s ease-out',
        'slide-up': 'slideUp 0.4s cubic-bezier(0.22, 1, 0.36, 1)',
        'pulse-soft': 'pulseSoft 2.4s ease-in-out infinite',
        eq1: 'eq 1.05s ease-in-out infinite',
        eq2: 'eq 0.95s ease-in-out infinite -0.2s',
        eq3: 'eq 0.85s ease-in-out infinite -0.4s',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        slideUp: {
          '0%': { opacity: 0, transform: 'translateY(12px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: 0.7 },
          '50%': { opacity: 1 },
        },
        eq: {
          '0%, 100%': { transform: 'scaleY(0.4)' },
          '50%': { transform: 'scaleY(1)' },
        },
      },
    },
  },
  daisyui: {
    themes: [
      {
        'downtiplx-dark': {
          primary: '#E5A00D',
          'primary-focus': '#CC7B19',
          'primary-content': '#1a0e00',
          secondary: '#9ca3af',
          'secondary-content': '#0a0a0a',
          accent: '#E5A00D',
          'accent-content': '#1a0e00',
          neutral: '#121212',
          'neutral-content': '#e5e7eb',
          'base-100': '#181818',
          'base-200': '#111111',
          'base-300': '#000000',
          'base-content': '#f4f4f5',
          info: '#3ABFF8',
          success: '#22c55e',
          warning: '#FBBD23',
          error: '#F87272',
          '--rounded-box': '1.25rem',
          '--rounded-btn': '9999px',
          '--rounded-badge': '9999px',
          '--btn-text-case': 'none',
          '--animation-btn': '0.25s',
          '--animation-input': '0.2s',
          '--border-btn': '1px',
          '--tab-radius': '0.75rem',
        },
      },
      {
        'downtiplx-light': {
          primary: '#CC7B19',
          'primary-focus': '#a55a10',
          'primary-content': '#ffffff',
          secondary: '#5d5d5d',
          'secondary-content': '#ffffff',
          accent: '#E5A00D',
          'accent-content': '#1a0e00',
          neutral: '#1f1f1f',
          'neutral-content': '#f4f4f5',
          'base-100': '#ffffff',
          'base-200': '#f5f6f7',
          'base-300': '#eaecef',
          'base-content': '#0f172a',
          info: '#3ABFF8',
          success: '#22c55e',
          warning: '#FBBD23',
          error: '#F87272',
          '--rounded-box': '1.25rem',
          '--rounded-btn': '9999px',
          '--rounded-badge': '9999px',
          '--btn-text-case': 'none',
          '--animation-btn': '0.25s',
          '--animation-input': '0.2s',
          '--border-btn': '1px',
          '--tab-radius': '0.75rem',
        },
      },
    ],
    darkTheme: 'downtiplx-dark',
  },
  plugins: [require('daisyui')],
}
